### ISSUE TITLE
Can you add a submodule for gridding the data

### ISSUE THREAD

**Issue by syedhamidali** [dopplerchase/DRpy#12]
Hi Randy,
I am wondering if you can develop a submodule for converting data to cartesian coordinates, with dimensions, x,y and z. or lat, long and z.
Best,
Syed

**Comment by dopplerchase** [comment]
Hello Syed, 

So you are asking to go from a satellite centric coordinate system (along-track, cross-track, range), to a x-y-z grid? 

Cheers, 
Randy
