### ISSUE TITLE
Very minor issue when downloading the data

### ISSUE THREAD

**Issue by syedhamidali** [dopplerchase/DRpy#25]
<img width="1190" alt="762DA5DB-050C-4D3C-8FC3-991E94C37633" src="https://user-images.githubusercontent.com/35923822/198371238-b5e85259-beb3-4bb9-b3c7-3a9d2c305282.png">
When downloading, it shows “Downloading 0 of 1” while it should be 1 of 1, right?

**Comment by syedhamidali** [comment]
I have corrected it, you may have to approve it!

**Comment by dopplerchase** [comment]
Issue fixed with pull!
