### ISSUE TITLE
colab and cartopy

### ISSUE THREAD

**Issue by swnesbitt** [dopplerchase/DRpy#4]
Cartopy was causing the notebook to restart in colab.

When I tried ax.coastlines() it was crashing.
 
I was able to get around the problem with this suggestion (https://stackoverflow.com/questions/60111684/geometry-must-be-a-point-or-linestring-error-using-cartopy):
 
Which meant using this:
```
!apt-get -qq install libproj-dev proj-data proj-bin libgeos-dev
!pip install Cython
!pip install --upgrade --force-reinstall shapely --no-binary shapely
!pip install cartopy
```

**Comment by dopplerchase** [comment]
Thanks Steve for finding this!
